### ISSUE TITLE
Bind Code

### ISSUE THREAD

**Issue by howlowck** [conarwelsh/nettuts-laravel4-and-backbone#1]
Is it common practice to put the bind in the routes.php? 

``` php
App::bind('PostRepositoryInterface', 'EloquentPostRepository');
App::bind('CommentRepositoryInterface', 'EloquentCommentRepository');
```

Or is there a better place to put them? like a service provider?

**Comment by conarwelsh** [comment]
I prefer to put them in a service provider, but this particular tutorial was already too long, so I did not want to introduce yet another concept such as service providers.

It is all preference really.

I have also created a `registry.php` file and placed them in there if I only have a quick application.
