### ISSUE TITLE
errors on sudo composer install --dev

### ISSUE THREAD

**Issue by krishnashetty0** [conarwelsh/nettuts-laravel4-and-backbone#11]
I get below errors when I try "sudo composer install --dev"
Please let me know any fixes. Thanks.

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for way/generators dev-master -> satisfiable by way/generators[dev-master].
    - conarwelsh/mustache-l4 dev-master requires illuminate/support ~4 -> satisfiable by laravel/framework[4.0.x-dev, v4.0.0, v4.0.0-BETA2, v4.0.0-BETA3, v4.0.0-BETA4, v4.0.1, v4.0.10, v4.0.11, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9], illuminate/support[4.0.x-dev, 4.1.x-dev, 4.2.x-dev, v4.0.0, v4.0.0-BETA2, v4.0.0-BETA3, v4.0.0-BETA4, v4.0.1, v4.0.10, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.13, v4.1.14, v4.1.15, v4.1.16, v4.1.17, v4.1.18, v4.1.19, v4.1.2, v4.1.20, v4.1.21, v4.1.22, v4.1.23, v4.1.24, v4.1.25, v4.1.26, v4.1.27, v4.1.28, v4.1.29, v4.1.3, v4.1.30, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.0-BETA1, v4.2.1, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].
    - Can only install one of: illuminate/support[5.0.x-dev, 4.0.x-dev].
    - Can only install one of: illuminate/support[5.0.x-dev, 4.1.x-dev].
    - Can only install one of: illuminate/support[5.0.x-dev, 4.2.x-dev].
    - Can only install one of: illuminate/support[v4.0.0, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.0.0-BETA2, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.0.0-BETA3, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.0.0-BETA4, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.0.1, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.0.10, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.0.2, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.0.3, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.0.4, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.0.5, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.0.6, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.0.7, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.0.8, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.0.9, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.1.0, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.1.1, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.1.10, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.1.11, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.1.12, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.1.13, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.1.14, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.1.15, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.1.16, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.1.17, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.1.18, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.1.19, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.1.2, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.1.20, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.1.21, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.1.22, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.1.23, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.1.24, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.1.25, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.1.26, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.1.27, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.1.28, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.1.29, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.1.3, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.1.30, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.1.4, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.1.5, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.1.6, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.1.7, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.1.8, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.1.9, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.2.0-BETA1, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.2.1, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.2.2, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.2.3, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.2.4, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.2.5, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.2.6, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.2.7, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.2.8, 5.0.x-dev].
    - Can only install one of: illuminate/support[v4.2.9, 5.0.x-dev].
    - don't install illuminate/support 5.0.x-dev|don't install laravel/framework 4.0.x-dev
    - don't install illuminate/support 5.0.x-dev|don't install laravel/framework v4.0.0
    - don't install illuminate/support 5.0.x-dev|don't install laravel/framework v4.0.0-BETA2
    - don't install illuminate/support 5.0.x-dev|don't install laravel/framework v4.0.0-BETA3
    - don't install illuminate/support 5.0.x-dev|don't install laravel/framework v4.0.0-BETA4
    - don't install illuminate/support 5.0.x-dev|don't install laravel/framework v4.0.1
    - don't install illuminate/support 5.0.x-dev|don't install laravel/framework v4.0.10
    - don't install illuminate/support 5.0.x-dev|don't install laravel/framework v4.0.11
    - don't install illuminate/support 5.0.x-dev|don't install laravel/framework v4.0.2
    - don't install illuminate/support 5.0.x-dev|don't install laravel/framework v4.0.3
    - don't install illuminate/support 5.0.x-dev|don't install laravel/framework v4.0.4
    - don't install illuminate/support 5.0.x-dev|don't install laravel/framework v4.0.5
    - don't install illuminate/support 5.0.x-dev|don't install laravel/framework v4.0.6
    - don't install illuminate/support 5.0.x-dev|don't install laravel/framework v4.0.7
    - don't install illuminate/support 5.0.x-dev|don't install laravel/framework v4.0.8
    - don't install illuminate/support 5.0.x-dev|don't install laravel/framework v4.0.9
    - way/generators dev-master requires illuminate/support ~5.0 -> satisfiable by illuminate/support[5.0.x-dev].
    - Installation request for conarwelsh/mustache-l4 dev-master -> satisfiable by conarwelsh/mustache-l4[dev-master]

**Comment by pschmidt88** [comment]
Can you post your `composer.json` file?
