### ISSUE TITLE
Conflicting requirements

### ISSUE THREAD

**Issue by brandonzylstra** [conarwelsh/nettuts-laravel4-and-backbone#6]
mustache-l4 and way/generators both require different versions of mustache/mustache:

```
root@laravel:/var/www# composer install --dev
Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for way/generators dev-master -> satisfiable by way/generators[dev-master].
    - way/generators dev-master requires mustache/mustache 2.4.* -> satisfiable by mustache/mustache[v2.4.0, v2.4.1].
    - Can only install one of: mustache/mustache[v2.4.0, dev-master].
    - Can only install one of: mustache/mustache[v2.4.1, dev-master].
    - conarwelsh/mustache-l4 dev-master requires mustache/mustache dev-master -> satisfiable by mustache/mustache[dev-master].
    - Installation request for conarwelsh/mustache-l4 dev-master -> satisfiable by conarwelsh/mustache-l4[dev-master].
```

**Comment by bsima** [comment]
way/generators [requires](https://github.com/JeffreyWay/Laravel-4-Generators/blob/master/composer.json) version 2.4 of mustache. Until @JeffreyWay updates his `composer.json` file in the package to use the dev-master version of mustache (which could be a while, seeing as how he's got 24 outstanding pull requests as it is), you're probably gonna have to do without generators, or manually install.

I tried to play with the version numbers to get it to work, but couldn't.

**Comment by brandonzylstra** [comment]
On Fri, Jan 17, 2014 at 12:06 AM, Ben Sima notifications@github.com wrote:

> way/generators requireshttps://github.com/JeffreyWay/Laravel-4-Generators/blob/master/composer.jsonrequires version 2.4 of mustache. Until
> @JeffreyWay https://github.com/JeffreyWay updates his composer.jsonfile in the package to use the dev-master version of mustache (which could
> be a while, seeing as how he's got 24 outstanding pull requests as it is),
> you're probably gonna have to do without generators, or manually install.
> 
> I tried to play with the version numbers to get it to work, but couldn't.
> 
> Can I be confident that dev-master will work?  If so, I can just change it
> in my own fork, and use that.

## 

Brandon Zylstra
brandon.zylstra@gmail.com

**Comment by bsima** [comment]
I honestly don't know, but you could try - no harm in trying. Please let me know what you find out.

**Comment by bsima** [comment]
Here's fork of @JeffreyWay's generators that requires the proper mustache version `dev-master`, maintained by @PepijnSenders

https://packagist.org/packages/pepijnsenders/generators

**Comment by brandonzylstra** [comment]
Thanks!

## 

Brandon Zylstra
616-916-4511

**Comment by spaiter** [comment]
bsima Thanx!

**Comment by spaiter** [comment]
Hi, just use https://packagist.org/packages/pepijnsenders/generators insted
of https://packagist.org/packages/way/generators.

in app config in providers section write as in case of way generator
'Way\Generators\GeneratorsServiceProvider'

update composer and it's all

2014-02-21 23:44 GMT+06:00 kamov notifications@github.com:

**Comment by kamov** [comment]
@spaiter thanks but I do already it.

I fork that generators and change mustache dependecies to dev-master

And that providers it's already included 

It's working, but as I said on other issue, I can see posts, but I can't add comments.

So after hours to make it work, the script in fact not work as should.

It's like backbone don't load events
